export const experienceArchive = [
  {
    title: "SRE ITS Official Website",
    subtitle: "Renewable Energy Organization Platform",
    description:
      "Orchestrated the full project lifecycle for the official Society of Renewable Energy ITS website. Directed a team of 11 developers to build the platform and the 2025 Open Registration feature, streamlining member recruitment.",
    year: 2025,
    role: "Director of Website Development Department",
    startDate: "2025-07-25",
    endDate: "Present",
    techStack: ["Next.js", "React", "Tailwind CSS", "Team Management", "UI/UX"],
    cover: "sreitsCover.mp4",
    slug: "sre-its-official",
    repoLink: null,
    liveLink: "https://www.sre-its.com",
  },
  {
    title: "Petroleum Integrated Days (Petrolida) 2025",
    subtitle: "International Energy Competition Website",
    description:
      "Led the Front-End development for an international-scale energy competition. Engineered multi-event registration funnels, real-time order tracking, and sliced high-fidelity UI designs into responsive Next.js pages.",
    year: 2025,
    role: "Staff of Frontend Development",
    startDate: "2024-10-18",
    endDate: "2025-05-18",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Zod",
      "React Hook Form",
      "TypeScript",
    ],
    cover: "Petrolida2025Cover2.mp4",
    slug: "petrolida-2025",
    repoLink: null,
    liveLink: "https://petrolida2025-fe.vercel.app",
  },
  {
    title: "A Renewal Agent (ARA) 6.0",
    subtitle: "IoT & Cyber Security Competition",
    description:
      "Served as Front-End Expert Staff for the largest annual technology event by HMIT ITS. Developed responsive interfaces and handled dynamic content for national-level competitions and seminars.",
    year: 2025,
    role: "Expert Staff of Frontend Development",
    startDate: "2024-10-31",
    endDate: "2025-06-20",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    cover: "ara6Cover",
    slug: "ara-6-0",
    repoLink: null,
    liveLink: "https://ara6-frontend.vercel.app",
  },
  {
    title: "Ini Lho ITS! 2025",
    subtitle: "University Introduction Event Platform",
    description:
      "Built the official event website to introduce ITS university life to high school students across Indonesia. Focused on component-based architecture and server-side rendering for optimal performance.",
    year: 2025,
    role: "Staff of Frontend Development",
    startDate: "2024-10-22",
    endDate: "2025-03-14",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    cover: "ilits2025Cover.mp4",
    slug: "ini-lho-its-2025",
    repoLink: null,
    liveLink: null,
  },
  {
    title: "BEM ITS Official Website",
    subtitle: "Student Executive Board Portal",
    description:
      "Operated as a key Front-End Developer in an agile team to build the primary digital communication channel for tens of thousands of ITS students.",
    year: 2025,
    role: "Staff of Website Development",
    startDate: "2025-03-23",
    endDate: "Present",
    techStack: ["Next.js", "React", "Tailwind CSS", "Agile"],
    cover: "bemitsCover",
    slug: "bem-its",
    repoLink: null,
    liveLink: "https://bem-its.com/",
  },
];
