export const projectArchive = [
  {
    title: "SRE ITS Official Website",
    subtitle: "Renewable Energy Organization Platform",
    description:
      "Orchestrated the full project lifecycle for the official Society of Renewable Energy ITS website. Directed a team of 11 developers to build the platform and the 2025 Open Registration feature, streamlining member recruitment.",
    year: 2025,
    startDate: "2025-07-01",
    endDate: "Present",
    techStack: ["Next.js", "React", "Tailwind CSS", "Team Management", "UI/UX"],
    cover: "/archive/sreItsCover.mp4",
    slug: "sre-its-official",
    repoLink: null,
    liveLink: null,
  },
  {
    title: "Petroleum Integrated Days (Petrolida) 2025",
    subtitle: "International Energy Competition Website",
    description:
      "Led the Front-End development for an international-scale energy competition. Engineered multi-event registration funnels, real-time order tracking, and sliced high-fidelity UI designs into responsive Next.js pages.",
    year: 2025,
    startDate: "2024-10-01",
    endDate: "2025-05-30",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Zod",
      "React Hook Form",
      "TypeScript",
    ],
    cover: "/archive/petrolida2025Cover2.mp4",
    slug: "petrolida-2025",
    repoLink: null,
    liveLink: "https://petrolida2025-fe.vercel.app",
  },
  {
    title: "Ini Lho ITS! 2025",
    subtitle: "University Introduction Event Platform",
    description:
      "Built the official event website to introduce ITS university life to high school students across Indonesia. Focused on component-based architecture and server-side rendering for optimal performance.",
    year: 2025,
    startDate: "2024-10-01",
    endDate: "2025-04-30",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    cover: "/archive/ilits2025Cover.mp4",
    slug: "ini-lho-its-2025",
    repoLink: null,
    liveLink: null,
  },
  {
    title: "A Renewal Agent (ARA) 6.0",
    subtitle: "IoT & Cyber Security Competition",
    description:
      "Served as Front-End Expert Staff for the largest annual technology event by HMIT ITS. Developed responsive interfaces and handled dynamic content for national-level competitions and seminars.",
    year: 2025,
    startDate: "2024-11-01",
    endDate: "2025-05-30",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    cover: "/archive/ara6Cover.png",
    slug: "ara-6-0",
    repoLink: null,
    liveLink: "https://ara6-frontend.vercel.app",
  },
  {
    title: "BEM ITS Official Website",
    subtitle: "Student Executive Board Portal",
    description:
      "Operated as a key Front-End Developer in an agile team to build the primary digital communication channel for tens of thousands of ITS students.",
    year: 2025,
    startDate: "2025-03-01",
    endDate: "Present",
    techStack: ["Next.js", "React", "Tailwind CSS", "Agile"],
    cover: "/archive/bemItsCover.png",
    slug: "bem-its",
    repoLink: null,
    liveLink: "https://bem-its.com/",
  },
  {
    title: "Antasena ITS Team Internship Special Task",
    subtitle: "Hydrogen Car Team Landing Page",
    description:
      "Developed a dynamic landing page using Laravel 11 and Blade components. Designed the UI in Figma and implemented responsive styling with Tailwind CSS.",
    year: 2024,
    startDate: "2024-01-01",
    endDate: "2024-03-01",
    techStack: ["Laravel 11", "Tailwind CSS", "Blade", "Figma"],
    cover: "/archive/antasenaCover.png",
    slug: "antasena-special-task",
    repoLink:
      "https://github.com/Ax3lrod/Special-Task-Web-Developer-Antasena-ITS-Team-2024",
    liveLink: null,
  },
  {
    title: "Eclipta (IT ITS 2023)",
    subtitle: "Batch Generation Website",
    description:
      "Developed a responsive website for the 2023 Information Technology students. Collaborated on the Hero Section and ensured smooth user experience using modern web technologies.",
    year: 2023,
    startDate: "2023-08-01",
    endDate: "2023-12-01",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    cover: "/archive/ecliptaCover.png",
    slug: "eclipta-2023",
    repoLink: null,
    liveLink: "https://eclipta.vercel.app/",
  },
  {
    title: "ShareITS (Genics Final Project)",
    subtitle: "Academic Resource Sharing Platform",
    description:
      "Led a team of developers to create a lecturer review and module sharing website. Managed the project lifecycle and contributed to Front-End development.",
    year: 2024,
    startDate: "2024-01-01",
    endDate: "2024-02-01",
    techStack: ["Next.js", "Tailwind CSS", "React", "Project Management"],
    cover: "/archive/shareitsCover.png",
    slug: "share-its-genics",
    repoLink: null,
    liveLink: null,
  },
  {
    title: "Yumochi",
    subtitle: "Mochi Business Landing Page",
    description:
      "Designed and developed a landing page for a Mochi business practicum. Created initial designs in Figma and implemented them using native web technologies.",
    year: 2024,
    startDate: "2024-01-01",
    endDate: "2024-02-01",
    techStack: ["HTML", "CSS", "JavaScript", "Figma"],
    cover: "/archive/yumochiCover.png",
    slug: "yumochi",
    repoLink: "https://github.com/Ax3lrod/pweb-HTML_CSS-p7-2024",
    liveLink: "https://yumochi.vercel.app/index.html",
  },
  {
    title: "Basic Media Schooling",
    subtitle: "Team Showcase Website",
    description:
      "Designed the web layout and collaborated with a team to showcase projects for the BMS course using native HTML/CSS.",
    year: 2023,
    startDate: "2023-09-01",
    endDate: "2023-10-01",
    techStack: ["HTML", "CSS", "JavaScript"],
    cover: "/archive/bmsCover.png",
    slug: "bms-team-20",
    repoLink: "https://github.com/Ax3lrod/KPP-BMS-Kelompok-20",
    liveLink: "https://kpp-bms-kelompok-20.vercel.app/",
  },
  {
    title: "Responsive Calculator",
    subtitle: "Utility Application",
    description:
      "A responsive calculator app featuring light and dark mode systems, built to practice React state management.",
    year: 2023,
    startDate: "2023-01-01",
    endDate: "2023-02-01",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    cover: "/archive/calculatorCover.mp4",
    slug: "responsive-calculator",
    repoLink: "https://github.com/Ax3lrod/calculator-app",
    liveLink: "https://ax3lrod-calculator-app.vercel.app/",
  },
];
