export const projectArchive = [
  {
    title: "Big Data Final Project",
    subtitle: "Steam Spam/Bot Review Detection System",
    description:
      "Architected a hybrid data lakehouse system (Kafka, PySpark, Trino) to process 6.4M+ reviews. Engineered an ML pipeline (Isolation Forest, K-Means, BERT) and built a FastAPI/Streamlit dashboard for real-time visualization.",
    year: 2024,
    role: "System Architect & Lead Developer",
    startDate: "2024-03-01",
    endDate: "2024-07-01",
    techStack: [
      "Kafka",
      "PySpark",
      "Trino",
      "FastAPI",
      "Docker",
      "Machine Learning",
    ],
    cover: "video1.mp4", // placeholder
    slug: "steam-review-detection",
    repoLink: null,
    liveLink: null,
  },
  {
    title: "SustainaMap",
    subtitle: "Air Pollution Awareness Web Application",
    description:
      "Developed an interactive map-based platform using Leaflet to monitor ecological data. Built location-based reporting features with Zod validation, delivering a modern UI with HeroUI and Framer Motion.",
    year: 2025,
    role: "Lead Frontend Developer",
    startDate: "2025-08-05",
    endDate: "2025-08-07",
    techStack: [
      "Next.js",
      "React",
      "Tailwind CSS",
      "Leaflet.js",
      "TypeScript",
      "Tanstack Query",
    ],
    cover: "sustainamapCover",
    slug: "sustainamap",
    repoLink: "https://github.com/Ax3lrod/sustainamap-fe",
    liveLink: null,
  },
  {
    title: "Virtual Try-On E-Commerce",
    subtitle: "WebAR Integration App",
    description:
      "Engineered a Next.js e-commerce prototype with Augmented Reality (WebAR) capabilities. Developed complex state management for cart operations and sliced a highly interactive UI with Framer Motion.",
    year: 2024,
    role: "Fullstack Developer",
    startDate: "2024-01-01",
    endDate: "2024-06-01",
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "WebAR",
    ],
    cover: "video2.mp4", // placeholder
    slug: "virtual-try-on-ecommerce",
    repoLink: null,
    liveLink: null,
  },
  {
    title: "ShareITS (GENICS 2.0)",
    subtitle: "Academic Resource Sharing Platform",
    description:
      "Led the backend development for an intensive 30-day bootcamp project. Architected the REST API and database integration using Node.js/Express, while actively contributing to frontend React integration.",
    year: 2024,
    role: "Backend Lead / Fullstack",
    startDate: "2024-10-16",
    endDate: "2024-12-09",
    techStack: ["Node.js", "Express", "TypeScript", "Next.js", "React"],
    cover: "shareitsCover",
    slug: "share-its-genics",
    repoLink: null,
    liveLink: null,
  },
];
